export default {
  COLLECTIONS: {
    BATTLEGROUNDS: 'battlegrounds',
    FACTIONS: 'factions',
    TEAMS: 'teams',
    LORE: 'lore',
    BATTLEREPORTS: 'battlereports',
    MISSIONS: 'missions',
    CRUSADES: 'crusades',
  },
  TEAMS: {
    BLOODANGELS: 'blood-angels',
    CULTOFTHELIGHTNINGEATERS: 'cult-of-the-lightning-eaters',
    DEATHGUARD: 'death-guard',
    DEATHGUARD: 'mortarians-anvil',
    HEARDSOFTHEWRITHINGNIGHT: 'heralds-of-the-writhing-night',
    NARTEKHDYNASTY: 'nartekh-dynasty',
    NURGLEUPRISING: 'nurgle-uprising',
    TAMREKHDYNASTY: 'tamrekh-dynasty',
    TEMPESTLEGION: 'tempest-legion',
    THEGAVINIUSKABAL: 'the-gavinius-kabal',
    THEGREATGREENWAAH: 'the-great-green-waah',
    THEOMNISSIAHSEXPLORATOR: 'the-omnissiahs-explorator',
    MECHANICUS: 'mechanicus',
    THEUNKNOWNCRAFTWORLD: 'the-unknown-craftworld',
    THECORONASELDAR: 'the-coronas-eldar',
    DARKANGELS: 'dark-angels',
    CHAOS: 'chaos',
    NECRON: 'necron',
  },
}
