export default {
  UNIT_TYPES: ['Hero', 'Wizard', 'Battleline', 'Other', 'Monster', 'Artillary'],
  STRONGHOLD_TYPES: ['Type A', 'Type B', 'Type C'],
  STARTING_SIZES: ['Vanguard', 'Medium', 'Large'],
  REALMS: [
    'Azyr',
    'Aqshy',
    'Shyish',
    'Ghyran',
    'Hysh',
    'Ghur',
    'Chamon',
    'Ulgu',
  ],
  FACTIONS: ['Chaos', 'Death', 'Order', 'Destruction'],
  SUB_FACTIONS: {
    CHAOS: [
      'Beasts of Chaos',
      'Blades of Khorne',
      'Disciples of Tzeentch',
      'Hedonites of Slaanesh',
      'Maggotkin of Nurgle',
      'Skaven',
      'Slaves to Darkness',
    ],
    DEATH: [
      'Flesh-Eater Courts',
      'Nighthaunt',
      'Ossiarch Bonereapers',
      'Soulblight Gravelords',
    ],
    DESTRUCTION: [
      'Gloomspite Gitz',
      'Ogor Mawtribes',
      'Orruk Warclans',
      'Sons of Behemat',
    ],
    ORDER: [
      'Cities of Sigmar',
      'Daughters of Khaine',
      'Fyreslayers',
      'Idoneth Deepkin',
      'Kharadron Overlords',
      'Lumineth Realm-lords',
      'Seraphon',
      'Stormcast Eternals',
      'Sylvaneth',
    ],
  },
}
